mmaCrudPin/Controllers/FightersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mmaCrudPin.Models;

namespace mmaCrudPin.Controllers
{
    public class FightersController : Controller
    {
        private readonly mmaDbContext _context;

        public FightersController(mmaDbContext context)
        {
            _context = context;
        }

        // GET: Index da početna bude prazna
        public async Task<IActionResult> Index(string name)
        {
            var rez = await _context.mmaFighters.Where(c => c.deleted == null && c.figtherName.StartsWith(name)).ToListAsync();
            if (!ModelState.IsValid)
            {
                return View("Search", rez);
            }
            return View("Index", rez);
            //return View(await _context.mmaFighters.ToListAsync()); vraća listu svih boraca
        }

        
        public IActionResult Details(int? id, string name)
        {

            //linq method syntax
            // _context.mmaFighters.Where(m => m.fighterId == id).FirstOrDefault();

            //linq query syntax
            var mmaFighter = (from m in _context.mmaFighters where m.fighterId == id select m).FirstOrDefault();
            return View(mmaFighter);
        }

        
        public IActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("figtherName,age,mma_record,category,created,worth_salary")] mmaFighter m)
        {
            
            if (ModelState.IsValid)
            {
                m.created = DateTime.Now;
                _context.Add(m);
                await _context.SaveChangesAsync();
                ViewBag.Message = "Borac je kreiran";
                return View("Index", new mmaFighter[] { m });
               
            }
            return View(m);
            
        }

        
        
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Find(id);
            //lamda linq method syntax 
            var mmaFighter = _context.mmaFighters.Where(i => i.fighterId == id).FirstOrDefault();
            if (mmaFighter == null)
            {
                return NotFound();
            }
            return View(mmaFighter);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("fighterId,figtherName,age,mma_record,category,created,modified,worth_salary")] mmaFighter m)
        {
            if (id != m.fighterId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    m.modified = DateTime.Now;
                    _context.mmaFighters.Update(m);
                    await _context.SaveChangesAsync();
                    ViewBag.Message = "Uspješno promijenjeno!";
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!mmaFighterExists(m.fighterId))
                    {
                        return NotFound();
                        
                    }
                    else
                    {
                        throw;
                    }
                }
                return View("Index", new mmaFighter[] { m });
            }
            return View(m);
            
        }


        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }
        //    var mma = await _context.mmaFighters.FirstOrDefaultAsync(m => m.fighterId == id);
        //    if (mma == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(mma);
        //}


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? Id, mmaFighter mf)
        {

            //using (mmaDbContext d = new mmaDbContext())
            //{

            //}
            //var mma = await _context.mmaFighters.FirstOrDefaultAsync(m => m.fighterId == id);
            //var mma = await _context.mmaFighters.Remove(x => x.fighterId == s.fighterId) mmaFigther s
            //s.deleted = Datetime.Now;

            //briše iz baze
            var mmaf = await _context.mmaFighters.FindAsync(Id);
            mf.deleted = DateTime.Now;
            _context.mmaFighters.Remove(mmaf);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }


        private bool mmaFighterExists(int id)
        {
            return _context.mmaFighters.Any(e => e.fighterId == id);
        }

        //Search
        public IActionResult Search(string name, mmaFighter mm, string mma_name, bool exist=true)
        {
            //Linq method syntax
            var rez = _context.mmaFighters.Where(m => m.deleted == null && m.figtherName.StartsWith(name)).ToList();
            mmaFighter mma = _context.mmaFighters.Where(k => k.figtherName == mm.figtherName && k.fighterId == mm.fighterId).FirstOrDefault();
            if (ModelState.IsValid)
            {
                if(mma == null)
                {
                    ViewBag.fighterName = mma_name;
                }
                if (exist)
                {
                    ViewBag.Message = "Traženi borac je pronađen.";
                }
                if(!exist || rez.Count == 0)
                {
                    ViewBag.Message = "<b>Traženog borca nismo pronašli.</b>";
                }

                ViewBag.fighterName = name;
                return View("Index", rez);
                
            }
            else
            {
                if (rez.Count == 0)
                    ViewBag.Message = "<b>Traženog borca nismo pronašli.</b>";
            }
            return View("Index", rez);
        }
    }
}

mmaCrudPin/Views/Fighters/Create.cshtml
@model mmaCrudPin.Models.mmaFighter

@{
    ViewData["Title"] = "Create";
}

<h2>Kreiraj MMA borca</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="figtherName" class="control-label"></label>
                <input asp-for="figtherName" class="form-control" />
                <span asp-validation-for="figtherName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="age" class="control-label"></label>
                <input asp-for="age" class="form-control" />
                <span asp-validation-for="age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mma_record" class="control-label"></label>
                <input asp-for="mma_record" class="form-control" />
                <span asp-validation-for="mma_record" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="category" class="control-label"></label>
                <select asp-for="category"
                        class="form-control"
                        asp-items="Html.GetEnumSelectList<Mma_category>()">
                    <option>Odaberi kategoriju</option>
                </select>
                <span asp-validation-for="category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="worth_salary" class="control-label"></label>
                <input asp-for="worth_salary" class="form-control" />
                <span asp-validation-for="worth_salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Kreiraj" class="btn btn-outline-primary" />
                <a class="btn btn-outline-success" asp-action="Index">Vrati na listu</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

mmaCrudPin/Views/Fighters/Delete.cshtml
@*@model mmaCrudPin.Models.mmaFighter

@{
    ViewData["Title"] = "Delete";
}
<h3>Jeste li sigurni da želite obrisati borca?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.figtherName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.figtherName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.category)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.mma_record)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.mma_record)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.age)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.age)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.created)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.created)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.modified)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.modified)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.deleted)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.deleted)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.worth_salary)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.worth_salary)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="fighterId" />
        <input type="submit" value="Izbriši" class="btn btn-outline-danger" /> 
        <a class="btn btn-outline-warning btn-sm" asp-action="Index">Vrati na listu</a>
    </form>
</div>*@

mmaCrudPin/Views/Fighters/Details.cshtml
@model mmaCrudPin.Models.mmaFighter

@{
    ViewData["Title"] = "Details";
}

<div>
    <h4>MMA borac</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.figtherName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.figtherName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.category)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.mma_record)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.mma_record)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.age)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.age)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.created)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.created)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.modified)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.modified)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.deleted)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.deleted)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.worth_salary)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.worth_salary)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-outline-primary btn-sm" asp-action="Edit" asp-route-id="@Model.fighterId">Uredi</a>
    <a class="btn btn-outline-warning btn-sm" asp-controller="Fighters" asp-action="Index" onclick="history.go(-1); return false;">Vrati na listu</a>
</div>

mmaCrudPin/Views/Fighters/Edit.cshtml
@model mmaCrudPin.Models.mmaFighter

@{
    ViewData["Title"] = "Edit";
}

<h4>Uredi MMA borca</h4>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit" method="post">
                <input type="hidden" asp-for="@Model.fighterId" />
                <div class="form-group">
                    <label asp-for="figtherName" class="control-label"></label>
                    <input asp-for="figtherName" class="form-control" />
                    <span asp-validation-for="figtherName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="age" class="control-label"></label>
                    <input asp-for="age" class="form-control" />
                    <span asp-validation-for="age" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="mma_record" class="control-label"></label>
                    <input asp-for="mma_record" class="form-control" />
                    <span asp-validation-for="mma_record" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="category" class="control-label"></label>
                    <select asp-for="category"
                            class="form-control"
                            asp-items="Html.GetEnumSelectList<Mma_category>()">
                        <option>Odaberi kategoriju</option>
                    </select>
                    <span asp-validation-for="category" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="created" class="control-label"></label>
                    <input asp-for="created" class="form-control" />
                    <span asp-validation-for="created" class="text-danger"></span>
                </div>               
                <div class="form-group">
                    <label asp-for="worth_salary" class="control-label"></label>
                    <input asp-for="worth_salary" class="form-control" />
                    <span asp-validation-for="worth_salary" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Snimi" class="btn btn-outline-success" />
                    <a class="btn btn-outline-primary btn-sm" asp-controller="Fighters" asp-action="Index" onclick="history.go(-1); return false;">Vrati na listu</a>
                </div>
            </form>
        </div>
    </div>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

mmaCrudPin/Views/Fighters/Index.cshtml
@model IEnumerable<mmaCrudPin.Models.mmaFighter>

@{
    ViewData["Title"] = "Index";
}

<h1 style="text-align:center;">Lista MMA boraca</h1>

<p>
    <a class="btn  btn-outline-success" asp-action="Create">Kreiraj novog MMA borca</a>
</p>
<form asp-action="Search" method="get">
    <div class="input-group mb-2">
        <input class="form-control" type="text" name="name" placeholder="Pretraži" value="@ViewBag.fighterName" />
        <span class="text-danger" data-valmsg-for="name" data-valmsg-replace="true"></span>
    </div>
</form>
@if (!string.IsNullOrEmpty(ViewBag.Message) || ViewBag.Message != null)
{
    <div class="alert alert-warning"><span>@Html.Raw(ViewBag.Message)</span></div>
}

<table class="table">
    <thead>
        <tr>
            <th>
                <b>@Html.DisplayNameFor(model => model.figtherName)</b>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.created)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.modified)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.worth_salary)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr id="row_@item.fighterId">
                <td>
                    <strong>@Html.DisplayFor(modelItem => item.figtherName)</strong>
                </td>
                <td>
                    <span class="badge badge-secondary">@Html.DisplayFor(modelItem => item.category)</span>
                </td>
                <td>
                    @item.created
                </td>
                <td>
                    @item.modified
                </td>
                <td>
                    <h5><span class="badge badge-success">@Html.DisplayFor(modelItem => item.worth_salary)</span></h5>
                </td>
                <td>
                    <a class="btn btn-outline-warning btn-sm" asp-action="Edit" asp-route-id="@item.fighterId">Uredi</a>
                    <a class="btn btn-outline-primary btn-sm" asp-action="Details" asp-route-id="@item.fighterId">Detalji</a>
                    <a class="btn btn-outline-danger btn-sm" role="button" id="deletebutton" onclick="Delete(@item.fighterId)">Izbriši</a>
                </td>
            </tr>
        }
    </tbody>
</table>
@foreach (var x in Model)
{
    <div class="modal fade" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    <h4>Jeste li sigurni da želite obrisati @x.figtherName?</h4>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-default" data-dismiss="modal">Odustani</a>
                    <input type="submit" class="btn btn-outline-danger" onclick="DeleteFighter()" value="Da" />
                </div>
            </div>
        </div>
    </div>

}


@*skriveno polje za spremanje fighterId*@
<input type="hidden" id="hiddenFighterId" />


@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");

        <script>

            var Delete = (FighterId) => {

                $("#hiddenFighterId").val(FighterId);
                $("#myModal").modal('show');

            }

            var DeleteFighter = () => {

                var FighterId = $("#hiddenFighterId").val();

                $.ajax({

                    type: "POST",
                    url: "/Fighters/Index",
                    data: { Id: FighterId },
                    success: (result) => {
                        $("#myModal").modal("hide");
                        $("#row_" + FighterId).remove();
                    }

                })

            }

        </script>
    }
}